services:
  api:
    build: .
    image: api_parcial
    container_name: api_parcial
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parcialdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  postgres:
    image: postgres:15
    container_name: postgres_parcial
    restart: always
    environment:
      POSTGRES_DB: parcialdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
